on:
  push:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/docker-publish.with-dot:latest

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        run: docker build . -t ${{ env.IMAGE }}

      - name: Login to docker.pkg.github.com
        run: docker login https://docker.pkg.github.com -u token --password-stdin <<< ${{ github.token }}

      - name: Publish image
        run: docker push ${{ env.IMAGE }}

